pub_rate: 1.0 # Optional
base_path: "" # Optional 
analyzers:
  nao_dcm_driver: 
    type: AnalyzerGroup
    path: Nao
    analyzers:
      battery:
        type: GenericAnalyzer
        path: Battery
        remove_prefix: nao_dcm_driver
        contains: Battery
      joints:
        type: GenericAnalyzer
        path: Joints
        remove_prefix: nao_dcm_driver
        contains: Joints
