romeo_dcm:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Controllers ------------------------------------------------
  NeckYaw_position_controller:
    type: position_controllers/JointPositionController
    joint: NeckYaw
    
  NeckPitch_position_controller:
    type: position_controllers/JointPositionController
    joint: NeckPitch

  HeadPitch_position_controller:
    type: position_controllers/JointPositionController
    joint: HeadPitch
    
  HeadRoll_position_controller:
    type: position_controllers/JointPositionController
    joint: HeadRoll

  LShoulderPitch_position_controller:
    type: position_controllers/JointPositionController
    joint: LShoulderPitch

  LElbowYaw_position_controller:
    type: position_controllers/JointPositionController
    joint: LElbowYaw

  LWristYaw_position_controller:
    type: position_controllers/JointPositionController
    joint: LWristYaw

  LHand_position_controller:
    type: position_controllers/JointPositionController
    joint: LHand

  LShoulderYaw_position_controller:
    type: position_controllers/JointPositionController
    joint: LShoulderYaw

  LElbowRoll_position_controller:
    type: position_controllers/JointPositionController
    joint: LElbowRoll

  RShoulderPitch_position_controller:
    type: position_controllers/JointPositionController
    joint: RShoulderPitch

  RElbowYaw_position_controller:
    type: position_controllers/JointPositionController
    joint: RElbowYaw

  RWristYaw_position_controller:
    type: position_controllers/JointPositionController
    joint: RWristYaw

  RHand_position_controller:
    type: position_controllers/JointPositionController
    joint: RHand

  RShoulderYaw_position_controller:
    type: position_controllers/JointPositionController
    joint: RShoulderYaw

  RElbowRoll_position_controller:
    type: position_controllers/JointPositionController
    joint: RElbowRoll

  LHipYaw_position_controller:
    type: position_controllers/JointPositionController
    joint: LHipYaw

  LHipRoll_position_controller:
    type: position_controllers/JointPositionController
    joint: LHipRoll

  LHipPitch_position_controller:
    type: position_controllers/JointPositionController
    joint: LHipPitch

  LKneePitch_position_controller:
    type: position_controllers/JointPositionController
    joint: LKneePitch

  LAnklePitch_position_controller:
    type: position_controllers/JointPositionController
    joint: LAnklePitch

  LAnkleRoll_position_controller:
    type: position_controllers/JointPositionController
    joint: LAnkleRoll

  RHipYaw_position_controller:
    type: position_controllers/JointPositionController
    joint: RHipYaw

  RHipRoll_position_controller:
    type: position_controllers/JointPositionController
    joint: RHipRoll

  RHipPitch_position_controller:
    type: position_controllers/JointPositionController
    joint: RHipPitch

  RKneePitch_position_controller:
    type: position_controllers/JointPositionController
    joint: RKneePitch

  RAnklePitch_position_controller:
    type: position_controllers/JointPositionController
    joint: RAnklePitch

  RAnkleRoll_position_controller:
    type: position_controllers/JointPositionController
    joint: RAnkleRoll

  TrunkYaw_position_controller:
    type: position_controllers/JointPositionContro$
    joint: TrunkYaw
